#!/bin/bash
gcc -o rm rm.c

touch for_test
test -f for_test || exit $?
./rm for_test
! test -f for_test || exit $?

touch for_test1 for_test2
test -f for_test1 || exit $?
test -f for_test2 || exit $?
./rm for_test1 for_test2
! test -f for_test1 || exit $?
! test -f for_test2 || exit $?

echo OK
