#!/bin/bash
set -e

gcc -Wall -o grep grep.c

diff <(cat ./grep.c | ./grep arg) <(cat ./grep.c | grep arg)
diff <(./grep arg grep.c) <(grep arg grep.c)

diff <(cat ./grep.c | ./grep r.*p) <(cat ./grep.c | grep r.*p)
diff <(./grep r.*p grep.c) <(grep r.*p grep.c)

diff <(cat ./grep.c | ./grep 'r.*p') <(cat ./grep.c | grep 'r.*p')
diff <(./grep 'r.*p' grep.c) <(grep 'r.*p' grep.c)

diff <(cat ./grep.c | ./grep fffff) <(cat ./grep.c | grep fffff)
diff <(./grep fffff grep.c) <(grep fffff grep.c)

# -i: ignore case option
diff <(echo thisisUppErcase | ./grep -i upper) <(echo thisisUppErcase | grep -i upper)

echo OK
