#!/bin/bash
set -e
gcc -o head head.c

# from stdin
diff <(cat head.c | ./head) <(cat head.c | head)
diff <(cat head.c | ./head) <(cat head.c | head -n 10)

# from stdin with -n
diff <(cat head.c | ./head -n 1) <(cat head.c | head -n 1)
diff <(cat head.c | ./head -n 5) <(cat head.c | head -n 5)
diff <(cat head.c | ./head -n 1000) <(cat head.c | head -n 1000)
diff <(cat head.c | ./head -n5) <(cat head.c | head -n5)

# from other file
diff <(./head head.c) <(head head.c)
diff <(./head head.c) <(head -n 10 head.c)

# from other file with -n
diff <(./head -n 1 head.c) <(head -n 1 head.c)
diff <(./head -n 5 head.c) <(head -n 5 head.c)
diff <(./head -n 1000 head.c) <(head -n 1000 head.c)
diff <(./head -n5 head.c) <(head -n5 head.c)

echo OK
